using Xunit;

namespace Dgt.Dojo.FizzBuzz
{
    public class ClassicTestData : TheoryData<int, string>
    {
        public ClassicTestData()
        {
            Add(  1, "1");
            Add(  2, "2");
            Add(  3, "Fizz");
            Add(  4, "4");
            Add(  5, "Buzz");
            Add(  6, "Fizz");
            Add(  7, "7");
            Add(  8, "8");
            Add(  9, "Fizz");
            Add( 10, "Buzz");
            Add( 11, "11");
            Add( 12, "Fizz");
            Add( 13, "13");
            Add( 14, "14");
            Add( 15, "FizzBuzz");
            Add( 16, "16");
            Add( 17, "17");
            Add( 18, "Fizz");
            Add( 19, "19");
            Add( 20, "Buzz");
            Add( 21, "Fizz");
            Add( 22, "22");
            Add( 23, "23");
            Add( 24, "Fizz");
            Add( 25, "Buzz");
            Add( 26, "26");
            Add( 27, "Fizz");
            Add( 28, "28");
            Add( 29, "29");
            Add( 30, "FizzBuzz");
            Add( 31, "31");
            Add( 32, "32");
            Add( 33, "Fizz");
            Add( 34, "34");
            Add( 35, "Buzz");
            Add( 36, "Fizz");
            Add( 37, "37");
            Add( 38, "38");
            Add( 39, "Fizz");
            Add( 40, "Buzz");
            Add( 41, "41");
            Add( 42, "Fizz");
            Add( 43, "43");
            Add( 44, "44");
            Add( 45, "FizzBuzz");
            Add( 46, "46");
            Add( 47, "47");
            Add( 48, "Fizz");
            Add( 49, "49");
            Add( 50, "Buzz");
            Add( 51, "Fizz");
            Add( 52, "52");
            Add( 53, "53");
            Add( 54, "Fizz");
            Add( 55, "Buzz");
            Add( 56, "56");
            Add( 57, "Fizz");
            Add( 58, "58");
            Add( 59, "59");
            Add( 60, "FizzBuzz");
            Add( 61, "61");
            Add( 62, "62");
            Add( 63, "Fizz");
            Add( 64, "64");
            Add( 65, "Buzz");
            Add( 66, "Fizz");
            Add( 67, "67");
            Add( 68, "68");
            Add( 69, "Fizz");
            Add( 70, "Buzz");
            Add( 71, "71");
            Add( 72, "Fizz");
            Add( 73, "73");
            Add( 74, "74");
            Add( 75, "FizzBuzz");
            Add( 76, "76");
            Add( 77, "77");
            Add( 78, "Fizz");
            Add( 79, "79");
            Add( 80, "Buzz");
            Add( 81, "Fizz");
            Add( 82, "82");
            Add( 83, "83");
            Add( 84, "Fizz");
            Add( 85, "Buzz");
            Add( 86, "86");
            Add( 87, "Fizz");
            Add( 88, "88");
            Add( 89, "89");
            Add( 90, "FizzBuzz");
            Add( 91, "91");
            Add( 92, "92");
            Add( 93, "Fizz");
            Add( 94, "94");
            Add( 95, "Buzz");
            Add( 96, "Fizz");
            Add( 97, "97");
            Add( 98, "98");
            Add( 99, "Fizz");
            Add(100, "Buzz");
        }
    }
}